# Generated by Django 3.2.5 on 2021-10-30 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trials', '0006_alter_userprofileinfo_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='trial_lead_firstname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
