# Generated by Django 3.2.5 on 2021-10-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0007_trial_trial_lead_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='trial_lead_firstname',
            new_name='trial_lead',
        ),
    ]
