# Generated by Django 3.2.5 on 2021-10-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0008_rename_trial_lead_firstname_trial_trial_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='exclusion_criteria',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trial',
            name='inclusion_criteria',
            field=models.TextField(),
        ),
    ]
