# Generated by Django 3.2.5 on 2021-10-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0009_auto_20211030_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trial',
            name='name',
            field=models.TextField(),
        ),
    ]
