# Generated by Django 3.2.5 on 2021-10-31 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0010_auto_20211030_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancertypes',
            name='body_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trials.bodyregion'),
        ),
    ]
