# Generated by Django 3.2.5 on 2021-10-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0011_cancertypes_body_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancertypes',
            options={'verbose_name': 'cancerType', 'verbose_name_plural': 'cancerTypes'},
        ),
    ]
