# Generated by Django 3.2.5 on 2021-11-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0012_alter_cancertypes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='Trial_ended',
            field=models.BooleanField(default=False),
        ),
    ]
