# Generated by Django 3.2.5 on 2021-11-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0014_alter_trial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
