# Generated by Django 3.2.5 on 2021-12-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0017_auto_20211205_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial_lead',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
