# Generated by Django 3.2.5 on 2021-12-05 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0018_alter_trial_lead_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='trial_lead',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='trials.trial_lead'),
        ),
    ]
