# Generated by Django 3.2.5 on 2021-12-05 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0019_alter_trial_trial_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='trial_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trials.trial_lead'),
        ),
    ]
